// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "dreampc/domain"

	mock "github.com/stretchr/testify/mock"
)

// CoreUsecase is an autogenerated mock type for the CoreUsecase type
type CoreUsecase struct {
	mock.Mock
}

type CoreUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CoreUsecase) EXPECT() *CoreUsecase_Expecter {
	return &CoreUsecase_Expecter{mock: &_m.Mock}
}

// MinBudget provides a mock function with given fields: ctx
func (_m *CoreUsecase) MinBudget(ctx context.Context) (domain.Money, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MinBudget")
	}

	var r0 domain.Money
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.Money, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.Money); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.Money)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreUsecase_MinBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinBudget'
type CoreUsecase_MinBudget_Call struct {
	*mock.Call
}

// MinBudget is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CoreUsecase_Expecter) MinBudget(ctx interface{}) *CoreUsecase_MinBudget_Call {
	return &CoreUsecase_MinBudget_Call{Call: _e.mock.On("MinBudget", ctx)}
}

func (_c *CoreUsecase_MinBudget_Call) Run(run func(ctx context.Context)) *CoreUsecase_MinBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CoreUsecase_MinBudget_Call) Return(_a0 domain.Money, _a1 error) *CoreUsecase_MinBudget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreUsecase_MinBudget_Call) RunAndReturn(run func(context.Context) (domain.Money, error)) *CoreUsecase_MinBudget_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoreUsecase creates a new instance of CoreUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoreUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoreUsecase {
	mock := &CoreUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
