// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "dreampc/domain"

	mock "github.com/stretchr/testify/mock"
)

// CoreRepository is an autogenerated mock type for the CoreRepository type
type CoreRepository struct {
	mock.Mock
}

type CoreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CoreRepository) EXPECT() *CoreRepository_Expecter {
	return &CoreRepository_Expecter{mock: &_m.Mock}
}

// MinBudget provides a mock function with no fields
func (_m *CoreRepository) MinBudget() (domain.Money, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MinBudget")
	}

	var r0 domain.Money
	var r1 error
	if rf, ok := ret.Get(0).(func() (domain.Money, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() domain.Money); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.Money)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreRepository_MinBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinBudget'
type CoreRepository_MinBudget_Call struct {
	*mock.Call
}

// MinBudget is a helper method to define mock.On call
func (_e *CoreRepository_Expecter) MinBudget() *CoreRepository_MinBudget_Call {
	return &CoreRepository_MinBudget_Call{Call: _e.mock.On("MinBudget")}
}

func (_c *CoreRepository_MinBudget_Call) Run(run func()) *CoreRepository_MinBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoreRepository_MinBudget_Call) Return(_a0 domain.Money, _a1 error) *CoreRepository_MinBudget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreRepository_MinBudget_Call) RunAndReturn(run func() (domain.Money, error)) *CoreRepository_MinBudget_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoreRepository creates a new instance of CoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoreRepository {
	mock := &CoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
