// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "dreampc/domain"

	mock "github.com/stretchr/testify/mock"
)

// CpuUsecase is an autogenerated mock type for the CpuUsecase type
type CpuUsecase struct {
	mock.Mock
}

type CpuUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CpuUsecase) EXPECT() *CpuUsecase_Expecter {
	return &CpuUsecase_Expecter{mock: &_m.Mock}
}

// BestByBudget provides a mock function with given fields: budget
func (_m *CpuUsecase) BestByBudget(budget domain.Money) (domain.Cpu, error) {
	ret := _m.Called(budget)

	if len(ret) == 0 {
		panic("no return value specified for BestByBudget")
	}

	var r0 domain.Cpu
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Money) (domain.Cpu, error)); ok {
		return rf(budget)
	}
	if rf, ok := ret.Get(0).(func(domain.Money) domain.Cpu); ok {
		r0 = rf(budget)
	} else {
		r0 = ret.Get(0).(domain.Cpu)
	}

	if rf, ok := ret.Get(1).(func(domain.Money) error); ok {
		r1 = rf(budget)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CpuUsecase_BestByBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BestByBudget'
type CpuUsecase_BestByBudget_Call struct {
	*mock.Call
}

// BestByBudget is a helper method to define mock.On call
//   - budget domain.Money
func (_e *CpuUsecase_Expecter) BestByBudget(budget interface{}) *CpuUsecase_BestByBudget_Call {
	return &CpuUsecase_BestByBudget_Call{Call: _e.mock.On("BestByBudget", budget)}
}

func (_c *CpuUsecase_BestByBudget_Call) Run(run func(budget domain.Money)) *CpuUsecase_BestByBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Money))
	})
	return _c
}

func (_c *CpuUsecase_BestByBudget_Call) Return(_a0 domain.Cpu, _a1 error) *CpuUsecase_BestByBudget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CpuUsecase_BestByBudget_Call) RunAndReturn(run func(domain.Money) (domain.Cpu, error)) *CpuUsecase_BestByBudget_Call {
	_c.Call.Return(run)
	return _c
}

// NewCpuUsecase creates a new instance of CpuUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCpuUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CpuUsecase {
	mock := &CpuUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
